name = "google-cloud-cli"

[[files]]
  source = "google-cloud-cli"
  target = ".local/bin/gcloud"
  mode = "755"
[[files]]
  source = "google-cloud-cli"
  target = ".local/bin/docker-credential-gcloud"
  mode = "755"
[[files]]
  source = "google-cloud-cli-config.volume"
  target = ".config/containers/systemd/google-cloud-cli-config.volume"
[[files]]
  source = "google-cloud-cli-kube.volume"
  target = ".config/containers/systemd/google-cloud-cli-kube.volume"
[[files]]
  source = "google-cloud-cli.container"
  target = ".config/containers/systemd/google-cloud-cli.container"
