name = "podman"

# podman

[[files]]
  source = "podman.bash"
  target = ".bashrc.d/50-podman.bash"
[[files]]
  source = "containers.conf"
  target = ".config/containers/containers.conf"
[[files]]
  source = "storage.conf"
  target = ".config/containers/storage.conf"
  template = true
