name = "atuin"

[[files]]
  source = "atuin.bash"
  # https://github.com/atuinsh/atuin/issues/2738#issuecomment-2876082481
  target = ".bashrc.d/60-atuin.bash"
[[files]]
  source = "config.toml"
  target = ".config/atuin/config.toml"
