name = "base"

# xdg-user-dirs

[[files]]
  source = "bashrc.bash"
  target = ".bashrc"
[[files]]
  source = "user-dirs.dirs"
  target = ".config/user-dirs.dirs"

[[hooks.pre_install]]
  command = "mkdir -p downloads"
