[theme]
theme = "solarized-dark"

[icons]
icons = "awesome6"

[[block]]
block = "cpu"
format = "$icon $barchart $utilization $frequency"
interval = 1

[[block]]
block = "memory"
format = "$icon $mem_used/$mem_total"
interval = 5

[[block]]
block = "net"
format = "$icon $ssid"
interval = 5

[[block]]
block = "battery"
format = "$icon $percentage"
full_format = "$icon $percentage"
empty_format = "$icon $percentage"
not_charging_format = "$icon $percentage"
interval = 5

[[block]]
block = "time"
format = "$icon $timestamp.datetime(f:'%F %T')"
interval = 1
