[theme]
theme = "solarized-dark"

[icons]
icons = "awesome6"

[[block]]
block = "cpu"
format = "$icon $barchart $utilization $frequency"
interval = 1

[[block]]
block = "memory"
format = "$icon $mem_used/$mem_total"
interval = 5

[[block]]
block = "time"
format = "$icon $timestamp.datetime(f:'%F %T')"
interval = 1
