name = "fcitx5"

[[files]]
  source = "50-fcitx5.bash"
  target = ".bashrc.d/50-fcitx5.bash"
[[files]]
  source = "config"
  target = ".config/fcitx5/config"
[[files]]
  source = "dictionary_list"
  target = ".local/share/fcitx5/skk/dictionary_list"
[[files]]
  source = "fcitx5.service"
  target = ".config/systemd/user/fcitx5.service"
[[files]]
  source = "profile"
  target = ".config/fcitx5/profile"
  mode = "100600"
[[files]]
  source = "skk.conf"
  target = ".config/fcitx5/conf/skk.conf"

[[hooks.post_install]]
  command = "systemctl --user daemon-reload && systemctl --user enable fcitx5.service"
[[hooks.pre_remove]]
  command = "systemctl --user disable fcitx5.service"
