name = "base"

[[files]]
  source = "bashrc.bash"
  target = ".bashrc"
[[files]]
  source = "50-ssh-agent.bash"
  target = ".bashrc.d/50-ssh-agent.bash"
[[files]]
  source = "50-starship.bash"
  target = ".bashrc.d/50-starship.bash"
[[files]]
  source = "user-dirs.dirs"
  target = ".config/user-dirs.dirs"
  pre_install = "mkdir -p ${HOME}/downloads"
